title: SOULTASTIC
author: SOULYANA
email: soulyana3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creative Technologist, Sunshine Dispenser, W

# social links
twitter_username: @S0ULTASTIC
github_username:  @soulyana

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
