title: 2019-04-22-s0ultastic.md
author: soulyana
email: soulyana@github.io
description: > # this means to ignore newlines until "baseurl:"
  Creative Technologist Thoughts 

# social links
twitter_username: @S0ULTASTIC
github_username:  @soulyana

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
